version: '3'

services:
  server:
    container_name: server
    build:
      context: server
    ports:
      - '127.0.0.1:5000:5000'
    environment:
      FLASK_PORT: 5000

  client:
    container_name: client
    build:
      context: client
    ports:
      - '127.0.0.1:3000:80'
    depends_on:
      - server